version: '3'
services:
  vue_app:
    build: .
    ports:
      - 9000:9000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    stdin_open: true
    tty: true
    command: /bin/sh
volumes:
  node_modules:
    driver: local